services:
  db:
    image: postgres:16-alpine
    container_name: vinicius_db
    restart: always
    environment:
      POSTGRES_USER: vinicius
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: portal_db
    ports:
      # - "5432:5432"
      - "127.0.0.1:5432:5432"
    volumes:
      - portal_data:/var/lib/postgresql/data

volumes:
  portal_data: